domain_path: C:\Users\nkgoe\cpre581_project\cpre581_project_platform\export\cpre581_project_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
